[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader_api = "0.11.5"
conquer-once = { version = "0.4.0", default-features = false }
log = "0.4.20"
printk = "0.3.2"
